name: Deploy

on:
  schedule:
    - cron: '0 7 * * *'
  push:
    branches:
      - master

jobs:
  deploy:
    if: github.repository == 'roblox-ts/roblox-ts'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Install NodeJS
        uses: actions/setup-node@master
        with:
          node-version: 10.x

      - name: Install node_modules
        run: npm install

      - name: Deploy
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "noreply@github.com"
          npm install roblox-ts@latest
          npm run build
          git add -A
          git diff-index --quiet HEAD || git commit -m "Update roblox-ts";
          git push https://${GIT_TOKEN}@github.com/roblox-ts/playground.git master
          npx gh-pages --dist=docs -r https://${GIT_TOKEN}@github.com/roblox-ts/playground.git
        env:
          GIT_TOKEN: ${{ secrets.git_token }}